apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/georgehanna1993/lesson8-jenkins-chart.git
    targetRevision: main
    path: sync-waves

  destination:
    server: https://kubernetes.default.svc
    namespace: sync-waves

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
